### ISSUE TITLE
Question: How to refresh content/abc/_index.md?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [kc0bfv/autophugo#13]
I have something like this ('content/nature/_index.md'):
```
---
title: "Natur"
date: 2021-02-19T13:34:21+01:00
albumthumb: "Nature/frederik-lower-tatFzQW0a3s-unsplash.jpg"
resources:
- src: Nature/frederik-lower-tatFzQW0a3s-unsplash.jpg
  phototitle: Grass cat
  description: This cat stalks through the grass
- src: Nature/geran-de-klerk-wYy3rvvgjAU-unsplash.jpg
  phototitle: Grass cat
  description: This cat stalks through the grass
---
```
If I add further pictures to 'assets/nature/' ... how to refresh _index.md (without loosing the manually added phototitles and descriptions)?
