### ISSUE TITLE
clarification / feature request => use custom link for images

### ISSUE THREAD

**Issue by rawwerks** [kc0bfv/autophugo#36]
I love this theme! I want to use it to display my NFT art, ideally with a link for each image that goes to the corresponding page on OpenSea when the image is clicked. Is this possible with the current theme?

**Comment by rawwerks** [comment]
maybe something like this?

````
resources:
- src: ineffable0000.png
  alt: Ineffable 0000
  phototitle: Ineffable 0000
  description: Ineffable 0000
  link: https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/100630620674349904143765932308874882507547312145348185146979691623647111282689
````
just having trouble finding the best place to put that resource variable in the layouts & partials
